const SECOND_IN_MILLIS = 1000;
const MINUTE_IN_MILLIS = SECOND_IN_MILLIS * 60;
const HOUR_IN_MILLIS = MINUTE_IN_MILLIS * 60;
const DAY_IN_MILLIS =  HOUR_IN_MILLIS * 24
const WEEK_IN_MILLIS = DAY_IN_MILLIS * 7;
const MONTH_IN_MILLIS = DAY_IN_MILLIS * 30;

export {SECOND_IN_MILLIS, MINUTE_IN_MILLIS, HOUR_IN_MILLIS, DAY_IN_MILLIS, WEEK_IN_MILLIS, MONTH_IN_MILLIS};